using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

[ExecuteInEditMode]
public class CheckpointSystem : MonoBehaviour
{
    public bool update = false; //this causes the editor to update this script when toggled
    public Checkpoint[] checkpointList_ThisIsAutoGenerated; //editor visible list of checkpoints, use Checkpoints.list in other scripts

    void Update()
    {
        if (!Application.isPlaying) //run this code only in editor
        {
            UpdateCheckpointList();
        }
    }

    void Start()
    {
        UpdateCheckpointList();
    }

    void UpdateCheckpointList()
    {
        Checkpoint[] tmpArr;
        tmpArr = FindObjectsOfType<Checkpoint>();   //find all checkpoint objects in level

        //sort array accending by number of checkpoints
        Array.Sort(tmpArr, (i1, i2) => (i2.checkpointNumber > i1.checkpointNumber ? -1 : 1));

        for (int i = 0; i < tmpArr.Length; i++)
        {
            if (tmpArr[i].checkpointNumber == -1)   //note checkpoints that are not numbered
            {
                Debug.LogError("Checkpoint not numbered, please set a value for 'checkpointNumber'", tmpArr[i].gameObject);
                continue;
            }
            for (int j = 0; j < tmpArr.Length; j++)
            {
                if (i == j) { continue; }   //dont compare to self
                if (tmpArr[i].checkpointNumber == tmpArr[j].checkpointNumber)   //alert when checkpoints share same value
                {
                    Debug.LogError("Two checkpoints share same number, please set different values for 'checkpointNumber'", tmpArr[j]);
                }
            }
        }

        ////convert sorted array of checkpoints to list of GameObjects
        //List<GameObject> finalList = new List<GameObject>();
        //foreach (Checkpoint item in tmpArr)
        //{
        //    finalList.Add(item.gameObject);
        //}

        checkpointList_ThisIsAutoGenerated = tmpArr;

        //store checkpointList in static Checkpoint object for global access
        Checkpoints.list = this.checkpointList_ThisIsAutoGenerated;
    }

}

// static class that holds list of checkpoints for racers
public static class Checkpoints
{
    public static Checkpoint[] list;
}
